<?php

namespace app\adminapi\controller;

use think\Controller;
use tools\jwt\Token;

class BaseApi extends Controller
{
    //无需进行登录检测的请求
    protected $no_login = ['login/login', 'login/captcha'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //允许的源域名
        header("Access-Control-Allow-Origin: *");
        //允许的请求头信息
        header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization");
        //允许的请求类型
        header('Access-Control-Allow-Methods: GET, POST, PUT,DELETE,OPTIONS,PATCH');
        //登录检测
        $this->checkLogin();
    }

    /**
     * 通用响应
     * @param int $code 错误码
     * @param string $msg 错误描述
     * @param array $data 返回数据
     */
    public function response($code=200, $msg='success', $data=[])
    {
        $res = [
            'code' => $code,
            'msg' => $msg,
            'data' => $data
        ];
        //以下两行二选一
        //echo json_encode($res, JSON_UNESCAPED_UNICODE);die;
        json($res)->send();die;
    }

    /**
     * 失败时响应
     * @param string $msg 错误描述
     * @param int $code 错误码
     */
    public function fail($msg='fail',$code=500)
    {
        return $this->response($code, $msg);
    }

    /**
     * 成功时响应
     * @param array $data 返回数据
     * @param int $code 错误码
     * @param string $msg 错误描述
     */
    public function ok($data=[], $code=200, $msg='success')
    {
        return $this->response($code, $msg, $data);
    }

    /**
     * 登录检测
     */
    private function checkLogin()
    {
        try {
            //登录检测
            //获取当前请求的控制器方法名称
            $path = strtolower($this->request->controller()).'/'.strtolower($this->request->action());
            if ( ! in_array($path, $this->no_login)){
                //需要做登录检测
                $user_id = Token::getUserId();
                if (empty($user_id)){
                    $this->fail('token验证失败', 403);
                }
                //将得到的用户id 放到请求信息中去  方便后续使用
                $this->request->get('user_id', $user_id);
                $this->request->post('user_id', $user_id);
            }
        }catch (\Exception $e){
            //token解析失败
            $this->fail('token解析失败', 404);
        }
    }
}
